### ISSUE TITLE
querySelectorAll

### ISSUE THREAD

**Issue by kennethkufluk** [woollybogger/Firebolt#2]
Have you considered using querySelectorAll instead of getElementsByClassName? It'll give you a selector syntax much more like jquery's, and it should be available in all your supported browsers.

**Comment by woollybogger** [comment]
Firebolt does use `document.querySelectorAll` right [here](https://github.com/woollybogger/Firebolt/blob/master/src/core.js#L1237) (where the private `querySelectorAll` function is defined [here](https://github.com/woollybogger/Firebolt/blob/master/src/core.js#L388-L391)).

You can use `Firebolt`/`$` just like you would with jQuery:
```js
$('div');
$('#some-id');
$('.some-class');
$('#some-id > .some-class');
```

**Comment by kennethkufluk** [comment]
Oh, cool. I was just reading the api docs. Assumed that since you were using $CLS then it didn't have an equivalent $ function. I stand corrected. :)
